# *awareness*::      <tt>string</tt>
# - 'Je sais ce que je veux faire'
# - 'Je ne sais pas ce que je veux faire'

# *experience*::     <tt>boolean</tt>
# - true
# - false

# *duration*::       <tt>string</tt>
# - 'Quelques mois'
# - '1 an'
# - "+ d'1 an"

# *engagement*::     <tt>string</tt>
# - 'Temps plein'
# - 'Mi-temps'
# - 'Flexible'

# *status*::         <tt>string</tt>
# - 'Sans activité'
# - 'Étudiant·e'
# - 'Lycéen·ne'
# - 'Salarié·e'
# - 'En formation'
# - 'Apprenti·e'
# - 'Autre'

# *age*::            <tt>integer</tt>
# 16, 26, 32, 45, etc...

# *handicap*::       <tt>boolean</tt>
# - true
# - false

# *last_class*::     <tt>string</tt>
# - 'Collège'
# - 'Lycée'
# - 'Études supérieures'
# - 'Aprentissage'
# - 'Autre'

# *pole_emploi*::    <tt>boolean</tt>
# - true
# - false

# *mission_locale*:: <tt>boolean</tt>
# - true
# - false

# *cap_emploi*::     <tt>boolean</tt>
# - true
# - false

# *apec*::           <tt>boolean</tt>
# - true
# - false

bij-de-bretigny:
  # Découvrir les métiers de l'animation
  travailler-mon-cv-et-ma-lettre-de-motivation:
    -
      -
        attribute: "sector"
        operator: "=="
        value: "Sport - Animation"
      -
        attribute: "experience"
        operator: "=="
        value: false
      -
        attribute: "status"
        operator: "in?"
        value:
          - "Sans activité"
          - "Étudiant·e"
          - "Lycéen·ne"
      -
        attribute: "last_class"
        operator: "in?"
        value:
          - "Collège"
          - "Lycée"
          - "Études supérieures"
          - "Aprentissage"

  definir-ton-projet-professionel:
    -
      -
        attribute: "experience"
        operator: "=="
        value: false
      -
        attribute: "status"
        operator: "in?"
        value:
          - "Sans activité"
          - "Étudiant·e"
          - "Lycéen·ne"
      -
        attribute: "last_class"
        operator: "in?"
        value:
          - "Collège"
          - "Lycée"
          - "Études supérieures"
          - "Aprentissage"
          - "Formation"

# Mission Locale Trois Vallées
acteur:
  # Faire le point sur tes compétences professionnelles en 2 jours
  offre-de-service:
    -
      -
        attribute: "experience"
        operator: "=="
        value: true
      -
        attribute: "status"
        operator: "in?"
        value:
          - "Sans activité"
          - "Étudiant·e"
      -
        attribute: "age"
        operator: "<="
        value: 25
      -
        attribute: "last_class"
        operator: "in?"
        value:
          - "Collège"
          - "Lycée"
          - "Études supérieures"
          - "Aprentissage"
          - "Formation"

  trouver-un-emploi-sans-diplome:
    -
      -
        attribute: "status"
        operator: "in?"
        value:
          - "Sans activité"
          - "Lycéen·ne"
          - "Collégien·ne"
      -
        attribute: "age"
        operator: "<="
        value: 25
      -
        attribute: "last_class"
        operator: "in?"
        value:
          - "Collège"
          - "Lycée"
